### PR TITLE
Fix model and add unit test

### PR DESCRIPTION
**Pull request by FT-Mystogan**
## Related Tickets:
- [#47440](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-intern-course-management/issues/47440)

## WHAT this PR does?
- Fix relation trong model và thêm unit test cho role và timetable.
- Chỉnh sửa cấu trúc folder

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Review by sonpham2k — APPROVED** [review]

**Comment by FT-Mystogan** [comment]
ready

**Comment by manhtd-1083** [comment]
bổ sung ticket ID

**Review by manhtd-1083 — COMMENTED** [review]
bổ sung ticket ID

**Review by huyenttm-0901 — APPROVED** [review]

**Comment by FT-Mystogan** [comment]
ready

**Pull request merged**
